import * as storage from '../vocabulary/storage.js';
import {LANGS} from '../vocabulary/model.js';
import {search} from '../dictionary/client.js';
import {rate,makeQueue} from '../study/scheduler.js';
import {loadStudyPreferences,saveStudyPreferences} from '../study/preferences.js';
import {gradeAnswer,quizCard,quizDirection} from '../study/quiz.js';
import {speakWord,stopSpeech} from './speech.js';
import {COURSE_LANGUAGES,loadCourse,findSkill,courseRef,matchesCourse} from '../course/duolingo.js';
import {defaultSpanishWords} from '../course/default-vocabulary.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let words=[],language='es',query='',results=[],searchError='',searched=false,busy=false,session=null,installEvent=null,studySettings=loadStudyPreferences(),courseLanguage='es',courseData=null,courseError='',courseBusy=false,courseSection=1,courseUnit=1,pendingCourseRef=null,courseAutoSearch=false,listPage=1;
const app=$('#app'),dialog=$('#dialog');
function notice(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('#toast').classList.remove('show'),4200)}
async function refresh(){words=await storage.all()}
function langSelect(id,value,all=false){return `<select id="${id}" aria-label="언어 선택">${all?'<option value="all">모든 언어</option>':''}${Object.entries(LANGS).map(([k,v])=>`<option value="${k}" ${k===value?'selected':''}>${v}</option>`).join('')}</select>`}
function title(k,h,sub){return `<div class="page-heading"><span class="eyebrow">${k}</span><h1>${h}</h1>${sub?`<p>${sub}</p>`:''}</div>`}
function empty(h,p){return `<div class="empty"><span class="empty-symbol" aria-hidden="true">▤</span><h2>${h}</h2><p>${p}</p></div>`}
function sourceLink(w){return w.source?`<a class="source" href="${esc(w.source)}" target="_blank" rel="noopener noreferrer">네이버 사전 원문 ↗</a>`:''}
function pronunciation(w){return [w.reading,w.pronunciation].filter(Boolean).map(x=>`<span>${esc(x)}</span>`).join(' · ')}
function render(){const page=location.hash.slice(1)||'search';document.querySelectorAll('nav a').forEach(a=>{a.classList.toggle('active',a.dataset.tab===page);a.setAttribute('aria-current',a.dataset.tab===page?'page':'false')});if(page==='vocabulary')renderVocabulary();else if(page==='study')renderStudyV2();else if(page==='course')renderCourse();else renderSearch()}
function renderSearch(){app.innerHTML=title('DISCOVER','어떤 단어나 숙어를 모아볼까요?','필요한 뜻만 골라 나의 단어장에 담아요.')+`<form id="search-form" class="search-panel"><div class="search-label">사전 언어 ${langSelect('language',language)}</div><div class="search-row"><div class="search-input-wrap"><input id="query" aria-label="검색할 단어나 숙어" placeholder="단어 또는 숙어를 입력하세요" value="${esc(query)}" maxlength="100" required autocomplete="off" enterkeyhint="search"><button id="clear-query" class="clear-query" type="button" aria-label="검색어 모두 지우기" title="검색어 모두 지우기" ${query&&!busy?'':'hidden'}>×</button></div><button class="primary" ${busy?'disabled':''}>${busy?'검색 중…':'검색'}</button></div><div class="search-foot"><span class="dot"></span>네이버 사전 실제 단어·숙어 검색 결과</div>${pendingCourseRef?`<div class="course-context">듀오링고 ${LANGS[pendingCourseRef.language]} 과정 · 섹션 ${pendingCourseRef.section} · 유닛 ${pendingCourseRef.selectedUnit}</div>`:''}<button id="open-course" class="course-launch" type="button">듀오링고 과정별 단어 →</button></form><section id="results" aria-live="polite"></section><div class="local-note">단어와 숙어는 이 기기에 저장돼요.<br>소중한 단어장은 가끔 JSON으로 백업해 주세요.</div>`;
 $('#language').disabled=busy;$('#query').disabled=busy;
 $('#language').onchange=e=>{language=e.target.value;pendingCourseRef=null;results=[];searched=false;searchError='';renderResults()};$('#query').oninput=e=>{query=e.target.value;pendingCourseRef=null;$('#clear-query').hidden=!query};
 $('#clear-query').onclick=()=>{query='';pendingCourseRef=null;results=[];searched=false;searchError='';$('#query').value='';$('#clear-query').hidden=true;renderResults();$('#query').focus()};$('#open-course').onclick=()=>location.hash='course';
 $('#search-form').onsubmit=async e=>{e.preventDefault();if(busy)return;query=$('#query').value.trim();if(!query)return;language=$('#language').value;busy=true;searchError='';results=[];searched=true;const targetLang=language;renderSearch();try{const d=await search(targetLang,query);results=d.results}catch(e){searchError=e.name==='TimeoutError'?'검색 응답이 늦어지고 있습니다. 잠시 후 다시 시도해 주세요.':e.message}finally{busy=false;if((location.hash||'#search')==='#search')renderSearch()}};renderResults();if(courseAutoSearch){courseAutoSearch=false;queueMicrotask(()=>$('#search-form')?.requestSubmit())}}
function renderResults(){const el=$('#results');if(!el)return;if(busy){el.innerHTML='<div class="empty"><div class="spinner"></div><p>사전에서 뜻을 가져오고 있어요.</p></div>';return}
 if(searchError){el.innerHTML=`<div class="error" role="alert"><h2>사전을 불러오지 못했어요</h2><p>${esc(searchError)}</p><p>검색 결과를 대신 만들어 표시하지 않습니다.</p></div>`;return}
 if(!searched){el.innerHTML=empty('오늘 만난 단어, 여기서 시작해요','검색한 뒤 뜻을 선택해야 저장됩니다.');return}
 if(!results.length){el.innerHTML=empty('검색 결과가 없어요','철자를 확인하거나 다른 형태로 검색해 주세요.');return}
 el.innerHTML=`<div class="section-label"><h2>검색 결과</h2><span>${results.length}개 · 뜻을 골라 저장</span></div>`+results.map((w,i)=>`<article class="word-card"><div class="word-top"><div><span class="tag">${esc(w.kind||'단어')}</span><h2 lang="${w.language}">${esc(w.headword)}</h2><div class="pron">${pronunciation(w)}</div></div><button class="add-button" data-add="${i}" aria-label="${esc(w.headword)} 뜻 선택">＋</button></div>${w.query!==w.headword?`<div class="query-link">검색어 ${esc(w.query)} → 표제어 ${esc(w.headword)}</div>`:''}<div class="pos">${esc(w.pos||'품사 정보 없음')}</div><ol class="meaning-preview">${w.senses.slice(0,3).map(s=>`<li>${esc(s.meaning)}</li>`).join('')}</ol>${w.example?`<div class="example"><p lang="${w.language}">${esc(w.example)}</p><p>${esc(w.translation)}</p></div>`:''}<div class="card-footer"><span>${esc(w.provider)}</span>${sourceLink(w)}</div></article>`).join('');el.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openEditor(results[Number(b.dataset.add)]));}
const courseKey=value=>String(value??'').normalize('NFC').toLocaleLowerCase();
function savedCourseWord(term){const key=courseKey(term);return words.find(w=>w.language===courseLanguage&&[w.headword,...(w.queries||[])].some(value=>courseKey(value)===key))}
function renderCourse(){
 stopSpeech();
 if(!courseData){app.innerHTML=title('COURSE GUIDE','듀오링고 과정별 단어','과정별 단어와 대표 뜻을 바로 학습할 수 있어요.')+`<div class="course-loading">${courseError?`<div class="error" role="alert"><h2>과정 자료를 열지 못했어요</h2><p>${esc(courseError)}</p><button id="retry-course">다시 시도</button></div>`:'<div class="spinner"></div><p class="muted center">과정 자료를 불러오고 있어요.</p>'}</div>`;if(courseError){$('#retry-course').onclick=()=>{courseError='';renderCourse()};return}if(!courseBusy){courseBusy=true;loadCourse(courseLanguage).then(data=>{courseData=data}).catch(error=>{courseError=error.message}).finally(()=>{courseBusy=false;if(location.hash==='#course')renderCourse()})}return}
 const section=courseData.sections.find(item=>item.number===courseSection)||courseData.sections[0];if(courseUnit>section.unitCount)courseUnit=1;const skill=findSkill(courseData,courseSection,courseUnit);if(!skill){courseUnit=1;renderCourse();return}
 const saved=skill.words.map(savedCourseWord).filter(word=>word&&matchesCourse(word,courseData.course,courseSection,courseUnit)),range=skill.unitFrom===skill.unitTo?`유닛 ${skill.unitFrom}`:`유닛 ${skill.unitFrom}–${skill.unitTo} 공통 단어`;
 app.innerHTML=`<button id="course-back" class="back-link">← 검색으로</button>${title('COURSE GUIDE','듀오링고 과정별 단어','과정별 단어와 대표 뜻을 학습하고 필요하면 수정하세요.')}<div class="course-picker"><label>학습 언어<select id="course-language">${Object.entries(COURSE_LANGUAGES).map(([key,name])=>`<option value="${key}" ${key===courseLanguage?'selected':''}>${name}</option>`).join('')}</select></label><label>섹션<select id="course-section">${courseData.sections.map(item=>`<option value="${item.number}" ${item.number===courseSection?'selected':''}>섹션 ${item.number} · ${item.cefr}</option>`).join('')}</select></label><label>유닛<select id="course-unit">${Array.from({length:section.unitCount},(_,index)=>{const number=index+1,title=findSkill(courseData,courseSection,number)?.units.find(item=>item.number===number)?.title||'';return `<option value="${number}" ${number===courseUnit?'selected':''}>${number}. ${esc(title)}</option>`}).join('')}</select></label></div><section class="course-skill"><span class="eyebrow">${esc(courseData.name)} · SECTION ${courseSection} · UNIT ${courseUnit}</span><h2>${esc(skill.units.find(item=>item.number===courseUnit)?.title||skill.goal)}</h2><p class="muted">${esc(skill.name)} · ${range} · ${skill.words.length}개 표현</p><div class="course-progress"><strong>${saved.length}</strong>개 저장됨${saved.length?`<button id="study-course" class="primary">저장한 단어 학습</button>`:''}</div></section><div class="course-words">${skill.words.map((term,index)=>{const stored=savedCourseWord(term),linked=stored&&matchesCourse(stored,courseData.course,courseSection,courseUnit);return `<div class="course-word"><span lang="${courseLanguage}">${esc(term)}${skill.meanings?.[index]?`<small class="course-meaning">${esc(skill.meanings[index])}</small>`:''}</span><button data-course-word="${index}" ${linked?'disabled':''}>${linked?'저장됨':stored?'과정에 연결':'사전 확인'}</button></div>`}).join('')}</div><p class="course-source">출처: <a href="${esc(courseData.source)}" target="_blank" rel="noopener noreferrer">Duome 듀오링고 ${esc(courseData.name)} 과정별 단어</a>${courseData.structureSource?` · <a href="${esc(courseData.structureSource)}" target="_blank" rel="noopener noreferrer">과정 구조</a>`:''}<br>${esc(courseData.note)}</p>`;
 $('#course-back').onclick=()=>location.hash='search';$('#course-language').onchange=e=>{courseLanguage=e.target.value;courseData=null;courseError='';courseSection=1;courseUnit=1;renderCourse()};$('#course-section').onchange=e=>{courseSection=Number(e.target.value);courseUnit=1;renderCourse()};$('#course-unit').onchange=e=>{courseUnit=Number(e.target.value);renderCourse()};document.querySelectorAll('[data-course-word]').forEach(button=>button.onclick=async()=>{const term=skill.words[Number(button.dataset.courseWord)],stored=savedCourseWord(term),ref=courseRef(courseData,skill,courseUnit);if(stored){await storage.save({...stored,courseRefs:[...(stored.courseRefs||[]),ref],updatedAt:Date.now()},{replace:true});await refresh();notice('저장된 단어를 이 과정에 연결했어요.');renderCourse();return}pendingCourseRef=ref;courseAutoSearch=true;language=courseLanguage;query=term;results=[];searched=false;searchError='';location.hash='search'});if($('#study-course'))$('#study-course').onclick=()=>startCourseStudy(saved);
}
function startCourseStudy(selected){const ids=makeQueue(selected,{from:1,to:selected.length,random:studySettings.order==='random'});session={mode:studySettings.mode,direction:studySettings.direction,queue:ids,total:ids.length,done:0,turn:0,flipped:false,result:null,repeated:new Set(),ratings:{know:0,unsure:0,unknown:0}};location.hash='study';renderStudyV2()}
function openEditor(word,editing=false){
 const w=structuredClone(word);$('#dialog-content').innerHTML=`<div class="dialog-top"><h2>${editing?'단어 수정':'뜻 선택 · 저장'}</h2><button id="close-dialog" class="icon-button" aria-label="닫기">×</button></div><form id="edit-form"><div class="field-pair"><label>표제어<input name="headword" value="${esc(w.headword)}" maxlength="150" required></label><label>검색어<input name="query" value="${esc(w.query)}" maxlength="150"></label></div><label>${w.language==='ja'?'읽는 법':w.language==='zh'?'병음 · 성조':'발음기호'}<input name="pron" value="${esc(w.language==='ja'?w.reading:w.pronunciation)}" placeholder="정보가 없으면 직접 입력할 수 있어요"></label><div class="field-pair"><label>품사<input name="pos" value="${esc(w.pos)}"></label><label>${w.language==='es'?'원형':'기본형'}<input name="lemma" value="${esc(w.lemma||w.headword)}"></label></div>${w.language==='es'?`<label>명사 성<input name="gender" value="${esc(w.gender)}" placeholder="남성 / 여성"></label>`:''}<fieldset><legend>저장할 뜻을 선택하세요</legend>${w.senses.map((s,i)=>`<div class="sense-edit"><label class="sense-check"><input type="checkbox" name="sense" value="${i}" ${editing||i===0?'checked':''}><span>${i+1}. ${esc(s.pos||'뜻')}</span></label><textarea name="meaning-${i}" aria-label="${i+1}번 뜻" rows="2">${esc(s.meaning)}</textarea></div>`).join('')}</fieldset><label>대표 예문<textarea name="example" rows="2">${esc(w.example)}</textarea></label><label>예문 한국어 뜻<textarea name="translation" rows="2">${esc(w.translation)}</textarea></label><p class="muted">제공되지 않은 정보는 비워 두었습니다. 저장 전에 수정할 수 있어요.</p><div id="editor-error" class="form-error" role="alert"></div><button class="primary wide" id="save-word">${editing?'수정 저장':'+ 단어장에 저장'}</button></form>`;
 $('#close-dialog').onclick=()=>dialog.close();$('#edit-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),selected=f.getAll('sense').map(Number);if(!selected.length){$('#editor-error').textContent='뜻을 하나 이상 선택해 주세요.';return}const senses=selected.map(i=>({...w.senses[i],meaning:String(f.get(`meaning-${i}`)).trim()}));if(senses.some(s=>!s.meaning)){$('#editor-error').textContent='선택한 뜻이 비어 있습니다.';return}
 const changed={...w,headword:String(f.get('headword')).trim(),query:String(f.get('query')).trim(),pos:String(f.get('pos')),lemma:String(f.get('lemma')),gender:String(f.get('gender')||''),example:String(f.get('example')),translation:String(f.get('translation')),senses,courseRefs:pendingCourseRef?[...(w.courseRefs||[]),pendingCourseRef]:(w.courseRefs||[]),updatedAt:Date.now()};if(w.language==='ja')changed.reading=String(f.get('pron'));else changed.pronunciation=String(f.get('pron'));
 $('#save-word').disabled=true;try{const result=await storage.save(changed,{replace:editing});await refresh();dialog.close();notice(result.duplicate?'이미 있는 단어에 새로운 뜻과 검색어를 합쳤어요.':'단어장에 저장했어요.');render()}catch(err){$('#editor-error').textContent=err.message;$('#save-word').disabled=false}};if(!dialog.open)dialog.showModal();}
let listLanguage='all',listFilter='';
function filteredWords(lang=listLanguage){return words.filter(w=>lang==='all'||w.language===lang)}
function renderVocabulary(){stopSpeech();const subset=filteredWords().filter(w=>[w.headword,w.query,w.reading,...w.senses.map(s=>s.meaning)].join(' ').toLowerCase().includes(listFilter.toLowerCase()));const pageCount=Math.max(1,Math.ceil(subset.length/50));listPage=Math.min(listPage,pageCount);const pageWords=subset.slice((listPage-1)*50,listPage*50);app.innerHTML=title('COLLECTION','차곡차곡, 내 단어장',`모은 단어·숙어 <strong>${words.length}</strong>개`)+`<div class="filters">${langSelect('list-language',listLanguage,true)}<input id="list-filter" type="search" aria-label="내 단어 찾기" placeholder="내 단어 찾기" value="${esc(listFilter)}"></div><div id="word-list">${subset.length?pageWords.map((w,i)=>`<article class="saved-card"><div class="saved-index">${filteredWords().indexOf(w)+1}</div><div class="saved-body"><div class="section-label"><span><span class="tag">${LANGS[w.language]}</span> <span class="tag kind-tag">${esc(w.kind||'단어')}</span>${(w.courseRefs||[]).slice(0,2).map(ref=>` <span class="tag course-tag">S${ref.section} · U${ref.unitFrom===ref.unitTo?ref.unitFrom:`${ref.unitFrom}–${ref.unitTo}`}</span>`).join('')}</span><span class="review-state">${(w.study?.due||0)<=Date.now()?'복습 가능':'다음 복습 '+new Date(w.study.due).toLocaleDateString('ko-KR')}</span></div><div class="saved-word-heading"><h2 lang="${w.language}">${esc(w.headword)}</h2><button class="pronounce-button" data-speak="${esc(w.id)}" aria-label="${esc(w.headword)} 발음 듣기" aria-pressed="false" title="기기의 음성으로 발음 듣기"><svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true"><path d="M11 4 5 9H2v6h3l6 5V4Zm4 4a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg><span>발음 듣기</span></button></div><div class="pron">${pronunciation(w)}</div><p>${w.senses.map(s=>esc(s.meaning)).join(' · ')}</p><div class="saved-actions"><button data-edit="${esc(w.id)}">수정</button><button data-delete="${esc(w.id)}">삭제</button>${sourceLink(w)}</div></div></article>`).join(''):empty(words.length?'맞는 단어가 없어요':'아직 모은 단어나 숙어가 없어요',words.length?'다른 언어나 검색어로 찾아보세요.':'검색에서 필요한 뜻을 골라 담아보세요.')}</div>${pageCount>1?`<div class="course-progress"><button id="prev-list" ${listPage===1?'disabled':''}>이전</button><span>${listPage} / ${pageCount} · ${subset.length}개</span><button id="next-list" ${listPage===pageCount?'disabled':''}>다음</button></div>`:''}`;
 $('#prev-list')?.addEventListener('click',()=>{listPage--;renderVocabulary();scrollTo(0,0)});$('#next-list')?.addEventListener('click',()=>{listPage++;renderVocabulary();scrollTo(0,0)});
 $('#list-language').onchange=e=>{listLanguage=e.target.value;listPage=1;renderVocabulary()};$('#list-filter').oninput=e=>{const start=e.target.selectionStart;listFilter=e.target.value;listPage=1;renderVocabulary();$('#list-filter').focus();$('#list-filter').setSelectionRange(start,start)};
 document.querySelectorAll('[data-speak]').forEach(b=>b.onclick=()=>{const w=words.find(w=>w.id===b.dataset.speak);speakWord(w,state=>{b.classList.toggle('speaking',state!=='idle');b.setAttribute('aria-pressed',String(state!=='idle'));b.setAttribute('aria-label',`${w.headword} ${state==='idle'?'발음 듣기':'발음 멈추기'}`);b.querySelector('span').textContent=state==='loading'?'준비 중…':state==='speaking'?'재생 중 · 중지':'발음 듣기';},notice)});
 document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{stopSpeech();openEditor(words.find(w=>w.id===b.dataset.edit),true)});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{stopSpeech();deleteDialog(words.find(w=>w.id===b.dataset.delete))});}
function deleteDialog(w){$('#dialog-content').innerHTML=`<div class="dialog-top"><h2>이 단어를 삭제할까요?</h2></div><p><strong>${esc(w.headword)}</strong>의 뜻과 학습 기록이 삭제됩니다.</p><div class="button-row"><button id="cancel-delete">취소</button><button id="confirm-delete" class="danger">삭제</button></div>`;dialog.showModal();$('#cancel-delete').onclick=()=>dialog.close();$('#confirm-delete').onclick=async()=>{try{await storage.remove(w.id);await refresh();session=null;dialog.close();notice('단어를 삭제했어요.');render()}catch(e){notice(e.message)}};}
let studyLanguage='all';
function renderStudy(){if(session){renderSession();return}const available=filteredWords(studyLanguage),due=available.filter(w=>(w.study?.due||0)<=Date.now()).length;app.innerHTML=title('DAILY PRACTICE','조금씩, 오래 기억하기','카드를 넘기고 얼마나 기억하는지 알려주세요.')+`<div class="study-summary"><div><span>모은 단어</span><strong>${available.length}</strong></div><div><span>복습 가능</span><strong>${due}</strong></div></div>${words.length?`<form id="study-form" class="study-settings"><label>학습 언어${langSelect('study-language',studyLanguage,true)}</label><label>학습 순서<select id="study-mode"><option value="range">범위 순서대로</option><option value="random">범위 안에서 랜덤</option></select></label><div class="field-pair"><label>시작 번호<input id="range-from" type="number" min="1" max="${available.length}" value="1" required></label><label>끝 번호<input id="range-to" type="number" min="1" max="${available.length}" value="${available.length}" required></label></div><p class="muted">선택한 언어의 저장 순서 기준입니다.</p><label class="check-line"><input id="due-only" type="checkbox">복습할 때가 된 단어만</label><div id="study-error" class="form-error" role="alert"></div><button class="primary wide" ${!available.length?'disabled':''}>학습 시작</button></form><div class="review-guide"><p><b>알아요</b> 다음 날부터 간격을 늘려 복습</p><p><b>헷갈려요</b> 이번 학습에서 한 번 더, 10분 뒤 복습</p><p><b>몰라요</b> 이번 학습에서 한 번 더, 1분 뒤 복습</p></div>`:empty('첫 단어를 담아볼까요?','단어장에 저장한 단어로 학습할 수 있어요.')}`;
 if(!words.length)return;$('#study-language').onchange=e=>{studyLanguage=e.target.value;renderStudy()};$('#study-form').onsubmit=e=>{e.preventDefault();try{const ids=makeQueue(available,{from:Number($('#range-from').value),to:Number($('#range-to').value),random:$('#study-mode').value==='random',dueOnly:$('#due-only').checked});if(!ids.length)throw new Error('이 범위에는 지금 복습할 단어가 없어요.');session={queue:ids,total:ids.length,done:0,flipped:false,repeated:new Set(),ratings:{know:0,unsure:0,unknown:0}};renderStudy()}catch(e){$('#study-error').textContent=e.message}};}
function renderSession(){if(!session.queue.length){app.innerHTML=title('WELL DONE','오늘의 학습을 마쳤어요','학습 결과를 저장하고 다음 복습에 반영했어요.')+`<div class="completion"><span class="complete-mark">✓</span><h2>${session.done}번의 기억 연습</h2><div class="rating-summary"><span>알아요 <b>${session.ratings.know}</b></span><span>헷갈려요 <b>${session.ratings.unsure}</b></span><span>몰라요 <b>${session.ratings.unknown}</b></span></div><button id="study-again" class="primary wide">학습 설정으로</button></div>`;$('#study-again').onclick=()=>{session=null;renderStudy()};return}
 const w=words.find(w=>w.id===session.queue[0]);if(!w){session.queue.shift();renderSession();return}app.innerHTML=`<div class="session-header"><button id="end-study">학습 나가기</button><span>남은 카드 ${session.queue.length}장</span></div><div class="progress"><div style="width:${session.done/(session.done+session.queue.length)*100}%"></div></div><p class="card-instruction">${session.flipped?'얼마나 기억했나요?':'카드를 눌러 뜻을 확인하세요'}</p><button id="flashcard" class="flashcard ${session.flipped?'flipped':''}" aria-label="${session.flipped?'단어 앞면 보기':'카드 뒤집기'}"><span class="tag">${LANGS[w.language]}</span><span class="flashword" lang="${w.language}">${esc(w.headword)}</span><span class="pron">${pronunciation(w)}</span>${session.flipped?`<span class="flash-meanings">${w.senses.map(s=>`<span>${esc(s.meaning)}</span>`).join('')}</span>${w.example?`<span class="flash-example">${esc(w.example)}<small>${esc(w.translation)}</small></span>`:''}`:'<span class="flip-hint">뜻 보기 ↻</span>'}</button><div class="rating-buttons"><button data-rating="unknown" ${!session.flipped?'disabled':''}><span>↺</span>몰라요</button><button data-rating="unsure" ${!session.flipped?'disabled':''}><span>≈</span>헷갈려요</button><button data-rating="know" ${!session.flipped?'disabled':''}><span>✓</span>알아요</button></div><p class="muted center">평가할 때마다 학습 기록이 바로 저장됩니다.</p>`;
 $('#flashcard').onclick=()=>{session.flipped=!session.flipped;renderSession()};$('#end-study').onclick=()=>{session=null;renderStudy()};document.querySelectorAll('[data-rating]').forEach(b=>b.onclick=async()=>{document.querySelectorAll('[data-rating]').forEach(x=>x.disabled=true);const rating=b.dataset.rating;try{const next={...w,study:rate(w.study,rating),updatedAt:Date.now()};await storage.save(next,{replace:true});await refresh();session.queue.shift();if(rating!=='know'&&!session.repeated.has(w.id)){session.queue.push(w.id);session.repeated.add(w.id)}session.done++;session.ratings[rating]++;session.flipped=false;renderSession()}catch(e){notice(e.message);renderSession()}});}
function rememberStudySettings(){studySettings=saveStudyPreferences({language:$('#study-language')?.value??studySettings.language,order:$('#study-order')?.value??studySettings.order,mode:$('#study-format')?.value??studySettings.mode,direction:$('#quiz-direction')?.value??studySettings.direction,dueOnly:$('#due-only')?.checked??studySettings.dueOnly})}
function renderStudyV2(){
 if(session){renderSessionV2();return}
 const available=filteredWords(studySettings.language),due=available.filter(w=>(w.study?.due||0)<=Date.now()).length;
 app.innerHTML=title('DAILY PRACTICE','조금씩, 오래 기억하기','카드 학습 또는 직접 입력 테스트로 기억을 확인하세요.')+`<div class="study-summary"><div><span>모은 단어</span><strong>${available.length}</strong></div><div><span>복습 가능</span><strong>${due}</strong></div></div>${words.length?`<form id="study-form" class="study-settings"><div class="study-option-grid"><label>학습 언어${langSelect('study-language',studySettings.language,true)}</label><label>학습 방식<select id="study-format"><option value="card" ${studySettings.mode==='card'?'selected':''}>카드 학습</option><option value="quiz" ${studySettings.mode==='quiz'?'selected':''}>해석 입력 테스트</option></select></label><label>학습 순서<select id="study-order"><option value="range" ${studySettings.order==='range'?'selected':''}>범위 순서대로</option><option value="random" ${studySettings.order==='random'?'selected':''}>범위 안에서 랜덤</option></select></label>${studySettings.mode==='quiz'?`<label>문제 방향<select id="quiz-direction"><option value="foreign-ko" ${studySettings.direction==='foreign-ko'?'selected':''}>외국어 → 한국어</option><option value="ko-foreign" ${studySettings.direction==='ko-foreign'?'selected':''}>한국어 → 외국어</option><option value="mixed" ${studySettings.direction==='mixed'?'selected':''}>양방향 섞기</option></select></label>`:''}</div><div class="field-pair"><label>시작 번호<input id="range-from" type="number" min="1" max="${Math.max(1,available.length)}" value="1" required></label><label>끝 번호<input id="range-to" type="number" min="1" max="${Math.max(1,available.length)}" value="${Math.min(20,Math.max(1,available.length))}" required></label></div><p class="muted">선택한 언어의 저장 순서 기준입니다. 학습 언어·방식·순서·문제 방향은 다음에도 그대로 열립니다.</p><label class="check-line"><input id="due-only" type="checkbox" ${studySettings.dueOnly?'checked':''}>복습할 때가 된 단어만</label><div id="study-error" class="form-error" role="alert"></div><button class="primary wide" ${!available.length?'disabled':''}>학습 시작</button></form><div class="review-guide"><p><b>카드 학습</b> 뜻을 본 뒤 알아요·헷갈려요·몰라요로 평가</p><p><b>입력 테스트</b> 한국어 또는 외국어 답을 직접 입력해 채점</p></div>`:empty('첫 단어나 숙어를 담아볼까요?','단어장에 저장한 내용으로 학습할 수 있어요.')}`;
 if(!words.length)return;
 $('#study-language').onchange=e=>{rememberStudySettings();renderStudyV2()};
 $('#study-format').onchange=e=>{rememberStudySettings();renderStudyV2()};
 $('#study-order').onchange=rememberStudySettings;
 if($('#quiz-direction'))$('#quiz-direction').onchange=rememberStudySettings;
 $('#due-only').onchange=rememberStudySettings;
 $('#study-form').onsubmit=e=>{e.preventDefault();try{rememberStudySettings();const selected=filteredWords(studySettings.language),ids=makeQueue(selected,{from:Number($('#range-from').value),to:Number($('#range-to').value),random:studySettings.order==='random',dueOnly:studySettings.dueOnly});if(!ids.length)throw new Error('이 범위에는 지금 복습할 단어나 숙어가 없어요.');session={mode:studySettings.mode,direction:studySettings.direction,queue:ids,total:ids.length,done:0,turn:0,flipped:false,result:null,repeated:new Set(),ratings:{know:0,unsure:0,unknown:0}};renderStudyV2()}catch(e){$('#study-error').textContent=e.message}};
}
async function finishStudyItem(word,rating){
 try{const next={...word,study:rate(word.study,rating),updatedAt:Date.now()};await storage.save(next,{replace:true});await refresh();session.queue.shift();if(rating!=='know'&&!session.repeated.has(word.id)){session.queue.push(word.id);session.repeated.add(word.id)}session.done++;session.turn++;session.ratings[rating]++;session.flipped=false;session.result=null;renderSessionV2()}catch(e){notice(e.message);renderSessionV2()}
}
function renderSessionV2(){
 if(!session.queue.length){app.innerHTML=title('WELL DONE','오늘의 학습을 마쳤어요','학습 결과를 저장하고 다음 복습에 반영했어요.')+`<div class="completion"><span class="complete-mark">✓</span><h2>${session.done}번의 기억 연습</h2><div class="rating-summary"><span>알아요 <b>${session.ratings.know}</b></span><span>헷갈려요 <b>${session.ratings.unsure}</b></span><span>몰라요 <b>${session.ratings.unknown}</b></span></div><button id="study-again" class="primary wide">학습 설정으로</button></div>`;$('#study-again').onclick=()=>{session=null;renderStudyV2()};return}
 const w=words.find(w=>w.id===session.queue[0]);if(!w){session.queue.shift();renderSessionV2();return}
 const progress=session.done/(session.done+session.queue.length)*100;
 if(session.mode==='quiz'){renderQuizSession(w,progress);return}
 app.innerHTML=`<div class="session-header"><button id="end-study">학습 나가기</button><span>남은 카드 ${session.queue.length}장</span></div><div class="progress"><div style="width:${progress}%"></div></div><p class="card-instruction">${session.flipped?'얼마나 기억했나요?':'카드를 눌러 뜻을 확인하세요'}</p><button id="flashcard" class="flashcard ${session.flipped?'flipped':''}" aria-label="${session.flipped?'단어 앞면 보기':'카드 뒤집기'}"><span class="tag">${LANGS[w.language]} · ${esc(w.kind||'단어')}</span><span class="flashword" lang="${w.language}">${esc(w.headword)}</span><span class="pron">${pronunciation(w)}</span>${session.flipped?`<span class="flash-meanings">${w.senses.map(s=>`<span>${esc(s.meaning)}</span>`).join('')}</span>${w.example?`<span class="flash-example">${esc(w.example)}<small>${esc(w.translation)}</small></span>`:''}`:'<span class="flip-hint">뜻 보기 ↻</span>'}</button><div class="rating-buttons"><button data-rating="unknown" ${!session.flipped?'disabled':''}><span>↺</span>몰라요</button><button data-rating="unsure" ${!session.flipped?'disabled':''}><span>≈</span>헷갈려요</button><button data-rating="know" ${!session.flipped?'disabled':''}><span>✓</span>알아요</button></div><p class="muted center">평가할 때마다 학습 기록이 바로 저장됩니다.</p>`;
 $('#flashcard').onclick=()=>{session.flipped=!session.flipped;renderSessionV2()};$('#end-study').onclick=()=>{session=null;renderStudyV2()};document.querySelectorAll('[data-rating]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-rating]').forEach(x=>x.disabled=true);finishStudyItem(w,b.dataset.rating)});
}
function renderQuizSession(w,progress){
 const direction=quizDirection(session.direction,session.turn),card=quizCard(w,direction),isKorean=direction==='ko-foreign',result=session.result;
 app.innerHTML=`<div class="session-header"><button id="end-study">학습 나가기</button><span>남은 문제 ${session.queue.length}개</span></div><div class="progress"><div style="width:${progress}%"></div></div><div class="quiz-card"><span class="tag">${isKorean?'한국어 → '+LANGS[w.language]:LANGS[w.language]+' → 한국어'}</span><p class="quiz-instruction">${isKorean?'알맞은 외국어를 입력하세요':'알맞은 한국어 뜻을 입력하세요'}</p><h2 class="quiz-prompt" lang="${card.promptLang}">${esc(card.prompt)}</h2>${!isKorean&&pronunciation(w)?`<div class="pron">${pronunciation(w)}</div>`:''}<form id="quiz-form"><label class="sr-only" for="quiz-answer">정답</label><input id="quiz-answer" autocomplete="off" autocapitalize="none" spellcheck="false" enterkeyhint="done" placeholder="${isKorean?'외국어 정답':'한국어 뜻'}" value="${esc(result?.input||'')}" ${result?'disabled':''} required><button class="primary wide" ${result?'hidden':''}>정답 확인</button></form>${result?`<div class="quiz-result ${result.correct?'correct':'wrong'}" role="status"><strong>${result.correct?'정답이에요!':'아쉬워요. 정답을 확인하세요.'}</strong><span>${esc(result.answerLabel)}</span></div><button id="next-question" class="primary wide">다음 문제</button>`:''}</div><p class="muted center">정답은 대소문자와 문장부호를 구분하지 않습니다.</p>`;
 $('#end-study').onclick=()=>{session=null;renderStudyV2()};
 if(!result){$('#quiz-form').onsubmit=e=>{e.preventDefault();const input=$('#quiz-answer').value,graded=gradeAnswer(w,direction,input);session.result={...graded,input};renderQuizSession(w,progress)};queueMicrotask(()=>$('#quiz-answer')?.focus())}
 else $('#next-question').onclick=()=>finishStudyItem(w,result.correct?'know':'unknown');
}
function openData(){
 $('#dialog-content').innerHTML=`<div class="dialog-top"><h2>단어장 보관하기</h2><button id="close-data" class="icon-button" aria-label="닫기">×</button></div><p>단어와 학습 기록은 이 브라우저에만 저장됩니다. 기기를 바꾸기 전에 백업해 주세요.</p><button id="export" class="primary wide">JSON 백업 다운로드</button><label class="file-label">백업 파일 복원<input id="import" type="file" accept="application/json,.json"></label><p class="muted">현재 단어를 유지하며 합칩니다. 같은 단어는 뜻을 합치고 현재 학습 기록을 유지합니다. 새 단어는 백업의 학습 기록을 가져옵니다.</p><div id="data-status" role="status"></div><hr><h3>홈 화면에 설치</h3><button id="install" ${installEvent?'':'hidden'} class="wide">모아 앱 설치</button><p class="muted">Android: 브라우저 메뉴의 ‘앱 설치’<br>iPhone: Safari 공유 메뉴 → ‘홈 화면에 추가’<br>한 번 열어둔 뒤에는 저장한 단어를 오프라인으로 학습할 수 있어요.</p>`;
 $('#close-data').onclick=()=>dialog.close();$('#export').onclick=async()=>{try{const b=await storage.backup(),url=URL.createObjectURL(new Blob([JSON.stringify(b,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`moa-vocab-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#data-status').textContent=`${b.words.length}개 단어의 백업을 다운로드했어요.`}catch(e){$('#data-status').textContent=e.message}};
 $('#import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>20*1024*1024)throw new Error('20MB 이하의 백업 파일을 선택해 주세요.');const value=JSON.parse(await f.text());const count=await storage.restore(value);await refresh();session=null;render();$('#data-status').textContent=`복원 완료: 새 단어 ${count}개, 전체 ${words.length}개`;}catch(e){$('#data-status').textContent=e instanceof SyntaxError?'올바른 JSON 파일이 아닙니다. 기존 단어는 그대로 유지됩니다.':e.message}finally{e.target.value=''}};
 $('#install').onclick=async()=>{if(installEvent){await installEvent.prompt();installEvent=null;$('#install').hidden=true}};dialog.showModal();}
$('#data-button').onclick=()=>{stopSpeech();openData()};window.addEventListener('hashchange',()=>{stopSpeech();render()});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e});
window.addEventListener('pagehide',stopSpeech);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopSpeech()});
window.addEventListener('online',()=>notice('다시 온라인이에요. 사전 검색을 사용할 수 있어요.'));window.addEventListener('offline',()=>notice('오프라인이에요. 저장한 단어는 계속 학습할 수 있어요.'));
try{
 if(localStorage.getItem('moa-spanish-defaults-v1')!=='done'){
  const data=await loadCourse('es');
  await storage.seedDefaults(defaultSpanishWords(data));
  localStorage.setItem('moa-spanish-defaults-v1','done');
 }
 await refresh();render();
}catch(e){app.innerHTML=`<div class="error" role="alert"><h1>기본 단어장을 열지 못했어요</h1><p>${esc(e.message)}</p><button onclick="location.reload()">다시 시도</button></div>`}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>notice('오프라인 준비를 마치지 못했어요. 인터넷 연결 후 새로고침해 주세요.'));


